spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
#  main:
#    allow-circular-references: true
logging:
  level:
    org.springframework:
      web: debug
      security: debug
      jdbc:
        core:
          JdbcTemplate: DEBUG
          StatementCreatorUtils: TRACE
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace
#    org.postgresql: debug
#server:
#  servlet:
#    session:
#      timeout: 15m
#      cookie:
#        http-only: true
#        secure: true