spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org.springframework:
      web: debug
      security: debug
      jdbc:
        core:
          JdbcTemplate: DEBUG
          StatementCreatorUtils: TRACE
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace