alter table if exists bucket
    drop constraint if exists FK_BUCKET__USER_ID;
alter table if exists buckets_items
    drop constraint if exists FK_BUCKETS_ITEMS__ITEM_ID;
alter table if exists buckets_items
    drop constraint if exists FK_BUCKETS_ITEMS__BUCKET_ID;
alter table if exists item_all_images_urls
    drop constraint if exists FK_ITEM_ALL_IMAGES_URLS__ITEM_ID;
alter table if exists item_params
    drop constraint if exists FK_ITEM_PARAMS__ITEM_ID;
alter table if exists order_parts
    drop constraint if exists FK_ORDER_PARTS__ITEM_ID;
alter table if exists order_parts
    drop constraint if exists FK_ORDER_PARTS__ORDER_ID;
alter table if exists orders
    drop constraint if exists FK_ORDERS__USER_ID;
alter table if exists orders_items
    drop constraint if exists FK_ORDERS_ITEMS__ITEM_ID;
alter table if exists orders_items
    drop constraint if exists FK_ORDERS_ITEMS__ORDER_ID;
alter table if exists roles_users
    drop constraint if exists FK_ROLES_USERS__ROLE_ID;
alter table if exists roles_users
    drop constraint if exists FK_ROLES_USERS__USER_ID;

drop table if exists bucket cascade;
drop table if exists buckets_items cascade;
drop table if exists item_all_images_urls cascade;
drop table if exists item_params cascade;
drop table if exists items cascade;
drop table if exists order_parts cascade;
drop table if exists orders cascade;
drop table if exists orders_items cascade;
drop table if exists role cascade;
drop table if exists roles_users cascade;
drop table if exists users cascade;



create table bucket
(
    id      int8 generated by default as identity,
    user_id int8,
    primary key (id)
);

create table buckets_items
(
    bucket_id int8 not null,
    item_id   int8 not null
);

create table item_all_images_urls
(
    item_id         int8 not null,
    all_images_urls varchar(255)
);

create table item_params
(
    item_id    int8         not null,
    params     bytea,
    params_key varchar(255) not null,
    primary key (item_id, params_key)
);

create table items
(
    id              int8 generated by default as identity,
    description     varchar(1024) not null,
    price           numeric(19, 2),
    title           varchar(64)   not null,
    title_image_url varchar(255),
    primary key (id)
);

create table order_parts
(
    id       int8 generated by default as identity,
    amount   numeric(19, 2),
    sum      numeric(19, 2),
    item_id  int8,
    order_id int8,
    primary key (id)
);

create table orders
(
    id           int8 generated by default as identity,
    created_date date,
    status       varchar(255),
    sum          numeric(19, 2),
    update_date  date,
    user_id      int8,
    primary key (id)
);

create table orders_items
(
    order_id int8 not null,
    item_id  int8 not null
);

create table role
(
    id   int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table roles_users
(
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id)
);


create table users
(
    id         int8 generated by default as identity,
    age        int4         not null check (age >= 18),
    email      varchar(255) not null,
    first_name varchar(128) not null,
    last_name  varchar(128) not null,
    password   varchar(128) not null,
    username   varchar(32)  not null,
    primary key (id)
);



alter table if exists users
    add constraint UK_USERS_EMAIL
        unique (email);
alter table if exists users
    add constraint UK_USERS_USERNAME
        unique (username);
alter table if exists bucket
    add constraint FK_BUCKET__USER_ID
        foreign key (user_id) references users;
alter table if exists buckets_items
    add constraint FK_BUCKETS_ITEMS__ITEM_ID
        foreign key (item_id) references items;
alter table if exists buckets_items
    add constraint FK_BUCKETS_ITEMS__BUCKET_ID
        foreign key (bucket_id) references bucket;
alter table if exists item_all_images_urls
    add constraint FK_ITEM_ALL_IMAGES_URLS__ITEM_ID
        foreign key (item_id) references items;
alter table if exists item_params
    add constraint FK_ITEM_PARAMS__ITEM_ID
        foreign key (item_id) references items;
alter table if exists order_parts
    add constraint FK_ORDER_PARTS__ITEM_ID
        foreign key (item_id) references items;
alter table if exists order_parts
    add constraint FK_ORDER_PARTS__ORDER_ID
        foreign key (order_id) references orders;
alter table if exists orders
    add constraint FK_ORDERS__USER_ID
        foreign key (user_id) references users;
alter table if exists orders_items
    add constraint FK_ORDERS_ITEMS__ITEM_ID
        foreign key (item_id) references items;
alter table if exists orders_items
    add constraint FK_ORDERS_ITEMS__ORDER_ID
        foreign key (order_id) references orders;
alter table if exists roles_users
    add constraint FK_ROLES_USERS__ROLE_ID
        foreign key (role_id) references role;
alter table if exists roles_users
    add constraint FK_ROLES_USERS__USER_ID
        foreign key (user_id) references users;