ALTER TABLE IF EXISTS bucket
    DROP constraint IF EXISTS FK_BUCKET__USER_ID;
ALTER TABLE IF EXISTS buckets_items
    DROP constraint IF EXISTS FK_BUCKETS_ITEMS__ITEMS_ID;
ALTER TABLE IF EXISTS buckets_items
    DROP constraint IF EXISTS FK_BUCKETS_ITEMS__BUCKET_ID;
ALTER TABLE IF EXISTS item_all_images_urls
    DROP constraint IF EXISTS FK_ITEM_ALL_IMAGES_URLS__ITEM_ID;
ALTER TABLE IF EXISTS item_params
    DROP constraint IF EXISTS FK_ITEM_PARAMS__ITEMS_ID;
ALTER TABLE IF EXISTS order_parts
    DROP constraint IF EXISTS FK_ORDER_PARTS__ITEM_ID;
ALTER TABLE IF EXISTS order_parts
    DROP constraint IF EXISTS FK_ORDER_PARTS__ORDER_ID;
ALTER TABLE IF EXISTS orders
    DROP constraint IF EXISTS FK_ORDERS__USER_ID;
ALTER TABLE IF EXISTS orders_items
    DROP constraint IF EXISTS FK_ORDERS_ITEMS__ITEM_ID;
ALTER TABLE IF EXISTS orders_items
    DROP constraint IF EXISTS FK_ORDERS_ITEMS_ORDER_ID;
ALTER TABLE IF EXISTS user_roles
    DROP constraint IF EXISTS FK_USER_ROLES__USER_ID;



DROP TABLE IF EXISTS bucket cascade;
DROP TABLE IF EXISTS buckets_items cascade;
DROP TABLE IF EXISTS item_all_images_urls cascade;
DROP TABLE IF EXISTS item_params cascade;
DROP TABLE IF EXISTS items cascade;
DROP TABLE IF EXISTS order_parts cascade;
DROP TABLE IF EXISTS orders cascade;
DROP TABLE IF EXISTS orders_items cascade;
DROP TABLE IF EXISTS user_roles cascade;
DROP TABLE IF EXISTS users cascade;



CREATE TABLE bucket
(
    id      int8 generated by default as identity,
    user_id int8,
    primary key (id)
);
CREATE TABLE buckets_items
(
    bucket_id int8 not null,
    item_id   int8 not null
);
CREATE TABLE item_all_images_urls
(
    item_id         int8 not null,
    all_images_urls varchar(255)
);
CREATE TABLE item_params
(
    item_id    int8         not null,
    params     bytea,
    params_key varchar(255) not null,
    primary key (item_id, params_key)
);
CREATE TABLE items
(
    id              int8 generated by default as identity,
    brand           varchar(255),
    description     varchar(1024) not null,
    model           varchar(255),
    price           numeric(19, 2),
    series          varchar(255),
    title           varchar(64)   not null,
    title_image_url varchar(255),
    primary key (id)
);
CREATE TABLE order_parts
(
    id       int8 generated by default as identity,
    amount   numeric(19, 2),
    sum      numeric(19, 2),
    item_id  int8,
    order_id int8,
    primary key (id)
);
CREATE TABLE orders
(
    id           int8 generated by default as identity,
    created_date date,
    status       varchar(255),
    sum          numeric(19, 2),
    update_date  date,
    user_id      int8,
    primary key (id)
);
CREATE TABLE orders_items
(
    order_id int8 not null,
    item_id  int8 not null
);
CREATE TABLE user_roles
(
    user_id int8 not null,
    roles   int4
);
CREATE TABLE users
(
    id         int8 generated by default as identity,
    age        int4         not null check (age >= 18),
    email      varchar(255) not null,
    first_name varchar(128) not null,
    last_name  varchar(128) not null,
    password   varchar(128) not null,
    username   varchar(32)  not null,
    primary key (id)
);



ALTER TABLE IF EXISTS users
    ADD CONSTRAINT UK_USERS__EMAIL UNIQUE (email);
ALTER TABLE IF EXISTS users
    ADD CONSTRAINT UK_USERS__USERNAME UNIQUE (username);
ALTER TABLE IF EXISTS bucket
    ADD CONSTRAINT FK_BUCKET__USER_ID foreign key (user_id) references users;
ALTER TABLE IF EXISTS buckets_items
    ADD CONSTRAINT FK_BUCKETS_ITEMS__ITEMS_ID foreign key (item_id) references items;
ALTER TABLE IF EXISTS buckets_items
    ADD CONSTRAINT FK_BUCKETS_ITEMS__BUCKET_ID foreign key (bucket_id) references bucket;
ALTER TABLE IF EXISTS item_all_images_urls
    ADD CONSTRAINT FK_ITEM_ALL_IMAGES_URLS__ITEM_ID foreign key (item_id) references items;
ALTER TABLE IF EXISTS item_params
    ADD CONSTRAINT FK_ITEM_PARAMS__ITEMS_ID foreign key (item_id) references items;
ALTER TABLE IF EXISTS order_parts
    ADD CONSTRAINT FK_ORDER_PARTS__ITEM_ID foreign key (item_id) references items;
ALTER TABLE IF EXISTS order_parts
    ADD CONSTRAINT FK_ORDER_PARTS__ORDER_ID foreign key (order_id) references orders;
ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT FK_ORDERS__USER_ID foreign key (user_id) references users;
ALTER TABLE IF EXISTS orders_items
    ADD CONSTRAINT FK_ORDERS_ITEMS__ITEM_ID foreign key (item_id) references items;
ALTER TABLE IF EXISTS orders_items
    ADD CONSTRAINT FK_ORDERS_ITEMS_ORDER_ID foreign key (order_id) references orders;
ALTER TABLE IF EXISTS user_roles
    ADD CONSTRAINT FK_USER_ROLES__USER_ID foreign key (user_id) references users;
