ALTER TABLE IF EXISTS bucket
	DROP CONSTRAINT IF EXISTS fk_bucket__user_id;
ALTER TABLE IF EXISTS buckets_items
	DROP CONSTRAINT IF EXISTS fk_buckets_items__items_id;
ALTER TABLE IF EXISTS buckets_items
	DROP CONSTRAINT IF EXISTS fk_buckets_items__bucket_id;
ALTER TABLE IF EXISTS item_all_images_urls
	DROP CONSTRAINT IF EXISTS fk_item_all_images_urls__item_id;
ALTER TABLE IF EXISTS item_params
	DROP CONSTRAINT IF EXISTS fk_item_params__items_id;
ALTER TABLE IF EXISTS order_parts
	DROP CONSTRAINT IF EXISTS fk_order_parts__item_id;
ALTER TABLE IF EXISTS order_parts
	DROP CONSTRAINT IF EXISTS fk_order_parts__order_id;
ALTER TABLE IF EXISTS orders
	DROP CONSTRAINT IF EXISTS fk_orders__user_id;
ALTER TABLE IF EXISTS orders_items
	DROP CONSTRAINT IF EXISTS fk_orders_items__item_id;
ALTER TABLE IF EXISTS orders_items
	DROP CONSTRAINT IF EXISTS fk_orders_items_order_id;
ALTER TABLE IF EXISTS user_roles
	DROP CONSTRAINT IF EXISTS fk_user_roles__user_id;



DROP TABLE IF EXISTS bucket CASCADE;
DROP TABLE IF EXISTS buckets_items CASCADE;
DROP TABLE IF EXISTS item_all_images_urls CASCADE;
DROP TABLE IF EXISTS item_params CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS order_parts CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS orders_items CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;



CREATE TABLE bucket
(
	id      int8 GENERATED BY DEFAULT AS IDENTITY,
	user_id int8,
	PRIMARY KEY (id)
);
CREATE TABLE buckets_items
(
	bucket_id int8 NOT NULL,
	item_id   int8 NOT NULL
);
CREATE TABLE item_all_images_urls
(
	item_id         int8 NOT NULL,
	all_images_urls varchar(255)
);
CREATE TABLE item_params
(
	item_id    int8         NOT NULL,
	params     bytea,
	params_key varchar(255) NOT NULL,
	PRIMARY KEY (item_id, params_key)
);
CREATE TABLE items
(
	id              int8 GENERATED BY DEFAULT AS IDENTITY,
	brand           varchar(255),
	model           varchar(255),
	series          varchar(255),
	price           numeric(19, 2),
	title           varchar(64)   NOT NULL,
	description     varchar(1024) NOT NULL,
	title_image_url varchar(255),
	PRIMARY KEY (id)
);
CREATE TABLE order_parts
(
	id       int8 GENERATED BY DEFAULT AS IDENTITY,
	item_id  int8,
	amount   numeric(19, 2),
	sum      numeric(19, 2),
	order_id int8,
	PRIMARY KEY (id)
);
CREATE TABLE orders
(
	id           int8 GENERATED BY DEFAULT AS IDENTITY,
	status       varchar(255),
	sum          numeric(19, 2),
	created_date date,
	update_date  date,
	user_id      int8,
	PRIMARY KEY (id)
);
CREATE TABLE orders_items
(
	order_id int8 NOT NULL,
	item_id  int8 NOT NULL
);
CREATE TABLE user_roles
(
	user_id int8 NOT NULL,
	roles   int4
);
CREATE TABLE users
(
	id         int8 GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(128) NOT NULL,
	last_name  varchar(128) NOT NULL,
	age        int4         NOT NULL CHECK (age >= 18),
	email      varchar(255) NOT NULL,
	username   varchar(32)  NOT NULL,
	password   varchar(128) NOT NULL,
	PRIMARY KEY (id)
);



ALTER TABLE IF EXISTS users
	ADD CONSTRAINT uk_users__email UNIQUE (email);
ALTER TABLE IF EXISTS users
	ADD CONSTRAINT uk_users__username UNIQUE (username);
ALTER TABLE IF EXISTS bucket
	ADD CONSTRAINT fk_bucket__user_id FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE IF EXISTS buckets_items
	ADD CONSTRAINT fk_buckets_items__items_id FOREIGN KEY (item_id) REFERENCES items;
ALTER TABLE IF EXISTS buckets_items
	ADD CONSTRAINT fk_buckets_items__bucket_id FOREIGN KEY (bucket_id) REFERENCES bucket;
ALTER TABLE IF EXISTS item_all_images_urls
	ADD CONSTRAINT fk_item_all_images_urls__item_id FOREIGN KEY (item_id) REFERENCES items;
ALTER TABLE IF EXISTS item_params
	ADD CONSTRAINT fk_item_params__items_id FOREIGN KEY (item_id) REFERENCES items;
ALTER TABLE IF EXISTS order_parts
	ADD CONSTRAINT fk_order_parts__item_id FOREIGN KEY (item_id) REFERENCES items;
ALTER TABLE IF EXISTS order_parts
	ADD CONSTRAINT fk_order_parts__order_id FOREIGN KEY (order_id) REFERENCES orders;
ALTER TABLE IF EXISTS orders
	ADD CONSTRAINT fk_orders__user_id FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE IF EXISTS orders_items
	ADD CONSTRAINT fk_orders_items__item_id FOREIGN KEY (item_id) REFERENCES items;
ALTER TABLE IF EXISTS orders_items
	ADD CONSTRAINT fk_orders_items_order_id FOREIGN KEY (order_id) REFERENCES orders;
ALTER TABLE IF EXISTS user_roles
	ADD CONSTRAINT fk_user_roles__user_id FOREIGN KEY (user_id) REFERENCES users;
